run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gofumpt
    - revive
    - gosec
  disable:
    - errorlint

linters-settings:
  gosec:
    excludes:
      - G104 # unhandled errors - we handle via explicit _ = ...
  revive:
    severity: warning

issues:
  exclude-dirs:
    - vendor
    - tmp
    - dist
    - bin
